### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by nnnnat** [nnnnat/simple-address-form#14]
# User Story
As a {user persona/role}, I want to {action/function} so that {outcome/biz value}

# Acceptance Criteria 
* Step one of the AC;
* Step two of the AC;
* Expected result;

# Task
* [x] Design user flow;
* [x] Some simple development task;
* [ ] Another simple development task;
* [ ] Complex development task: ##15
